### ISSUE TITLE
perl dependency failures

### ISSUE THREAD

**Issue by jeisner** [jbohren/jhpulse-linux#9]
When using this package (or when following the instructions at http://engineering.jhu.edu/jhpulse/), I get the following error.  

```
$ ~/.jhpulse/jhpulse
Can't locate URI/Escape.pm:   Permission denied at /usr/share/perl5/URI.pm line 22.
BEGIN failed--compilation aborted at /usr/share/perl5/URI.pm line 22.
Compilation failed in require at (eval 14) line 2.
Compilation failed in require at /usr/share/perl5/HTTP/Request.pm line 3.
Compilation failed in require at /usr/share/perl5/LWP/UserAgent.pm line 10.
BEGIN failed--compilation aborted at /usr/share/perl5/LWP/UserAgent.pm line 10.
Compilation failed in require at /usr/share/perl5/LWP/Simple.pm line 26.
BEGIN failed--compilation aborted at /usr/share/perl5/LWP/Simple.pm line 26.
Compilation failed in require at /home/jason/.jhpulse/jhpulse line 62.
BEGIN failed--compilation aborted at /home/jason/.jhpulse/jhpulse line 62.
```

Not sure what's going on, since URI/Escape.pm appears to be installed:

```
$ ls -l /usr/share/perl5/URI/Escape.pm
-rw-r--r-- 1 root root 6644 Feb 11  2012 /usr/share/perl5/URI/Escape.pm
$ sudo perl -MCPAN -e 'install URI::Escape'
Reading '/home/jason/.cpan/Metadata'
  Database was generated on Mon, 08 Jun 2015 08:53:17 GMT
URI::Escape is up to date (3.31).
```

**Comment by ddagunts** [comment]
I think the error "Permission denied" is symbolic of a permissions issue.  Check the permissions of the entire path to /usr/share/perl5/URI/Escape.pm - perhaps you have a 700 somewhere, because the perms on the file are correct.

Are you running some advanced ACLs? SELinux / AppArmor?

Finally, please post the output of: find `/usr/bin/perl -e '{print join $/, grep {/[^.]/} @INC}'` -name '*pm' 2>/dev/null

In any case, this looks very much like an issue with your local installation of perl (modules) and not with the jhpulse script itself.

**Comment by ddagunts** [comment]
<code> find `/usr/bin/perl -e '{print join $/, grep {/[^.]/} @INC}'` -name '*pm' 2>/dev/null </code>

**Comment by jeisner** [comment]
Permissions are fine (755 on directories, 644 on files).

I assume you meant
    find $(/usr/bin/perl -e '{print join $/, grep {/[^.]/} @INC}') -name
'*pm*' 2>/dev/null
The output is attached.  The perl command by itself returns
```
/home/jason/lib/perl
/etc/perl
/usr/local/lib/perl/5.18.2
/usr/local/share/perl/5.18.2
/usr/lib/perl5
/usr/share/perl5
/usr/lib/perl/5.18
/usr/share/perl/5.18
/usr/local/lib/site_perl
```

**Comment by chichilalescu** [comment]
I remember having a problem because of the suid thing (I think it's suid, no longer sure). anyway: is jhpulse installed on the root partition, or is your home folder on a different partition?

**Comment by jeisner** [comment]
My home folder is on its own partition.  The jhpulse script is presumably on that partition too, as ~/.jhpulse/jhpulse .

**Comment by chichilalescu** [comment]
ok. in your /etc/fstab, on the line for /home, remove the "nosuid", then reboot and try again. dmitry had to come see my computer in person to figure this out...

**Comment by chichilalescu** [comment]
actually, I think you need to reinstall jhpulse after rebooting, then try again.

**Comment by ddagunts** [comment]
Could be that, just check mounts.  Also your home directory has to be /home/<username> - I don't think it's gonna work otherwise.

**Comment by ddagunts** [comment]
And yes, I don't know remember how the permissions are set anymore, if there your home was mounted nosuid noguid reinstall the script to be safe.

**Comment by ddagunts** [comment]
From the readme:

Will not work if your home directory is not /home/username/ (very rare).
Will not work if your home partition is mounted with nosuid, noexec, etc. (very rare).

**Comment by jeisner** [comment]
None of those apply to me.
The problem does seem to be with Perl. 
I get the error simply from `perl -e 'use URI::Encode'`, and it is specifically a permissions error.
In fact I get the same error for any Perl package of the form URI::Foo, and only those packages.
So there must be something wrong with the permissions of the URI directory or its files, but these look the same as all of URI's sister directories ... I am mystified.

**Comment by ddagunts** [comment]
`sudo apt-get --reinstall install perl` ?
maybe
`sudo apt-get --reinstall install perl5`

**Comment by ddagunts** [comment]
also `strace perl -e 'use URI::Encode'`

**Comment by jeisner** [comment]
I tried
   sudo apt-get --reinstall install perl5
which changed the timestamp on /usr/share/perl5 but not on its contents.
I still get the same permissions error when running `perl -e 'use URI::Escape'`.
I *don't* get it if I use sudo, but I can't find any permissions issues that look wrong or are different in the sister directories.

**Comment by ddagunts** [comment]
http://askubuntu.com/questions/489941/permission-denied-running-perl
http://www.perlmonks.org/?node_id=1080639

"I understand that if one of the directories in the @INC path is inaccessible, the search for Config.pm (or any module) is abandoned. So check whether any of the directories is not readable by "all".
Strangely enough, a non-existent directory name in the @INC path is no problem."

**Comment by ddagunts** [comment]
same goes for PERLLIB directories apparently as well

**Comment by jeisner** [comment]
**Solved**
Thanks for letting me know about strace.  That turned up the problem: bad permissions on /usr/local/share/perl/5.18.2/URI, where /usr/local/share/perl/5.18.2 showed up earlier in @INC.  (I had already checked the directories in @INC because of the same advice that you found, but not their subdirs.)

I'll try running jhpulse again now.

**Comment by ddagunts** [comment]
pretty much my primary debugging tool, use it well :)

**Comment by jeisner** [comment]
And, jhpulse now works and gives me access.  Thanks very much, Dmitry (and Cristian), for all your time helping me track down something that wasn't a jhpulse problem at all.  I hope it comes in handy in future. :-/

**Comment by ddagunts** [comment]
You're very welcome, glad to help!
